ZETES_FEET_PATH = ../zetes/zetesfeet/target
ZETES_WINGS_PATH = ../zetes/zeteswings/target

APPLICATION_NAME = Tiny\ Viewer
BINARY_NAME = tinyview
ENTRY_CLASS = tinyviewer/TinyViewerApplication

TARGET = target

all: package

include $(ZETES_WINGS_PATH)/ZetesWings.mk

.SILENT: