ZETES_FEET_PATH = ../zetes/zetesfeet/target-$(CLASSPATH)
ZETES_WINGS_PATH = ../zetes/zeteswings/target-$(CLASSPATH)

APPLICATION_NAME = Tiny\ Viewer
BINARY_NAME = tinyview
ENTRY_CLASS = tinyviewer/TinyViewerApplication

TARGET = target-$(CLASSPATH)

all: package

include $(ZETES_WINGS_PATH)/ZetesWings.mk

#.SILENT: