ZETES_PATH = ../zetes

APPLICATION_NAME = Snake
BINARY_NAME = snake
ENTRY_CLASS = snake/SnakeApplication

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app

.PHONY: 
