ZETES_PATH = ../zetes

APPLICATION_NAME = DropFile
BINARY_NAME = dropfile
ENTRY_CLASS = dropfile/DropFileApplication

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app
