ZETES_FEET_PATH = ../zetes/zetesfeet/target-$(CLASSPATH)
ZETES_HANDS_PATH = ../zetes/zeteshands/target-$(CLASSPATH)

APPLICATION_NAME = BellardPI
BINARY_NAME = bellardpi
ENTRY_CLASS = bellardpi/Main

TARGET = target-$(CLASSPATH)

all: app

include $(ZETES_HANDS_PATH)/ZetesHands.mk
include ../zetes/common-scripts/ideconf/ideconf.mk

#.SILENT: