ZETES_PATH = ../zetes

APPLICATION_NAME = BellardPI
BINARY_NAME = bellardpi
ENTRY_CLASS = bellardpi/Main

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_HANDS_PATH)/ZetesHands.mk

all: app
