ZETES_PATH = ../zetes

APPLICATION_NAME = HTMLViewer
BINARY_NAME = htmlview
ENTRY_CLASS = htmlview/HTMLApplication

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app
