ZETES_PATH = ../zetes

APPLICATION_NAME = LiteHTML\ Demo
BINARY_NAME = litehtml-demo
ENTRY_CLASS = zetes/wings/litehtml/swt/demo/DemoMainWindow

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app
