ZETES_PATH = ../zetes

APPLICATION_NAME = Quadratic
BINARY_NAME = quadratic
ENTRY_CLASS = quadratic/QuadraticApplication

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app
