ZETES_PATH = ../zetes

APPLICATION_NAME = parrot-server
BINARY_NAME = parrot-server
ENTRY_CLASS = parrot/server/Main

all: app

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_HANDS_PATH)/ZetesHands.mk

