ZETES_PATH = ../zetes

APPLICATION_NAME = Ara
BINARY_NAME = ara
ENTRY_CLASS = parrot/ara/AraApplication

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app
